name: BluestarAPI
version: '${project.version}'
main: me.lanzhi.bluestarapi.internal.BluestarAPI
api-version: 1.13
softdepend:
  - CoreProtect
  - ProtocolLib
website: https://github.com/lanzhi6/BluestarAPI