# 这是一个github actions脚本，用于构建和发布java项目
name: Build and Release

# 触发条件为创建或更新release
on:
  release:
    types: [created, edited]

# 定义一个job
jobs:
  build-and-release:
    strategy:
      matrix:
        module: [BluestarAPI-Bukkit-injector,BluestarAPI-plugin,BluestarAPI-injector,BluestarAPI-net,BluestarAPI-kotlin]
    # 运行环境为ubuntu-latest
    runs-on: ubuntu-latest
    # 定义一个步骤
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2
      # 设置java环境为java17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      # 使用mvn clean build构建项目
      - name: Build with Maven
        run: mvn clean build
      # 遍历每个模块，将target文件夹下的jar文件上传到release
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          # 获取release的url
          release_url: ${{ github.event.release.url }}
          # 获取release的token
          token: ${{ secrets.GITHUB_TOKEN }}
          # 获取每个模块的jar文件
          file: ${{ matrix.module }}/target/${{ matrix.module }}-${{ github.event.release.tag_name }}.jar
          # 获取每个模块的名称
          name: ${{ matrix.module }}-${{ github.event.release.tag_name }}.jar
