name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package --quiet

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            is_release=true
          else
            is_release=false
          fi
          
          for file in $(find . -name "*-*.jar" -path "./target/*"); do
            module=$(echo $file | awk -F '/' '{print $3}')
            filename=$(basename -- "$file")
          
            if $is_release; then
              tag_name=$version
            else
              tag_name="pre-release-$version"
            fi
          
            echo "Uploading $filename as a release asset for module $module, tag $tag_name"
            gh release upload $tag_name $file -n "$module-$version.jar"
          done
